#############################################################################
# Makefile for building: GsTLAppli
# Generated by qmake (2.01a) (Qt 4.5.0) on: Sun Nov 1 16:46:28 2009
# Project:  GsTLAppli.pro
# Template: subdirs
# Command: /usr/bin/qmake -unix -o Makefile GsTLAppli.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-GsTLAppli

GsTLAppli//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) GsTLAppli/ || $(MKDIR) GsTLAppli/ 
	cd GsTLAppli/ && $(QMAKE) GsTLAppli.pro -unix -o $(MAKEFILE)
sub-GsTLAppli-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) GsTLAppli/ || $(MKDIR) GsTLAppli/ 
	cd GsTLAppli/ && $(QMAKE) GsTLAppli.pro -unix -o $(MAKEFILE)
sub-GsTLAppli: GsTLAppli//$(MAKEFILE) FORCE
	cd GsTLAppli/ && $(MAKE) -f $(MAKEFILE)
sub-GsTLAppli-make_default: GsTLAppli//$(MAKEFILE) FORCE
	cd GsTLAppli/ && $(MAKE) -f $(MAKEFILE) 
sub-GsTLAppli-make_first: GsTLAppli//$(MAKEFILE) FORCE
	cd GsTLAppli/ && $(MAKE) -f $(MAKEFILE) first
sub-GsTLAppli-all: GsTLAppli//$(MAKEFILE) FORCE
	cd GsTLAppli/ && $(MAKE) -f $(MAKEFILE) all
sub-GsTLAppli-clean: GsTLAppli//$(MAKEFILE) FORCE
	cd GsTLAppli/ && $(MAKE) -f $(MAKEFILE) clean
sub-GsTLAppli-distclean: GsTLAppli//$(MAKEFILE) FORCE
	cd GsTLAppli/ && $(MAKE) -f $(MAKEFILE) distclean
sub-GsTLAppli-install_subtargets: GsTLAppli//$(MAKEFILE) FORCE
	cd GsTLAppli/ && $(MAKE) -f $(MAKEFILE) install
sub-GsTLAppli-uninstall_subtargets: GsTLAppli//$(MAKEFILE) FORCE
	cd GsTLAppli/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: GsTLAppli.pro .qmake.cache /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		.qmake.cache \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf
	$(QMAKE) -unix -o Makefile GsTLAppli.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
.qmake.cache:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile GsTLAppli.pro

qmake_all: sub-GsTLAppli-qmake_all FORCE

make_default: sub-GsTLAppli-make_default FORCE
make_first: sub-GsTLAppli-make_first FORCE
all: sub-GsTLAppli-all FORCE
clean: sub-GsTLAppli-clean FORCE
distclean: sub-GsTLAppli-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-GsTLAppli-install_subtargets FORCE
uninstall_subtargets: sub-GsTLAppli-uninstall_subtargets FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

