##############################################################
# Automatically generated by qmake Sun May 19 20:55:49 2002
##############################################################

TEMPLATE = subdirs

SUBDIRS = utils appli math grid geostat actions extra/qwt extra/qtplugins filters gui extra/gui main
